name: Build and Deploy ASP.NET Core App to Azure Web Apps

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '7.0'  # Using a stable version of .NET
  NODE_VERSION: '20.x'   # Updated Node.js version
  APP_NAME: cgwebapplive
  AZURE_WEBAPP_SLOT: Production

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build .NET application
        run: dotnet build --configuration Release

      - name: Publish .NET application
        run: dotnet publish -c Release -o publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-publish-output
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment: 
      name: ${{ env.AZURE_WEBAPP_SLOT }}
      url: ${{ steps.deploy_to_webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dotnet-publish-output

      - name: Deploy to Azure Web App
        id: deploy_to_webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C8E0D68917ED4F73890074527BFC7EDB }}
          package: .

      - name: Check deployment status
        if: ${{ steps.deploy_to_webapp.outcome }} != 'success'
        run: echo "Deployment failed. Check logs for details."
        continue-on-error: true
